[[models]]
id = "gpt-5.5"
name = "GPT-5.5"
provider = "openai-local"
description = "Custom GPT-5.5 compatible model."
reasoning_effort = "medium"
supported_reasoning_efforts = ["low", "medium", "high", "xhigh"]
context_window = 272000
truncation_token_limit = 10000
priority = 0
visibility = "list"
shell_type = "shell_command"
web_search_tool_type = "text"
supported_in_api = true
supports_reasoning_summaries = true
default_reasoning_summary = "none"
support_verbosity = true
default_verbosity = "low"
supports_parallel_tool_calls = true
supports_image_detail_original = true
supports_search_tool = true
input_modalities = ["text", "image"]

[[models]]
id = "gpt-5.4-mini"
name = "GPT-5.4 Mini"
provider = "openai-local"
description = "Custom GPT-5.4 Mini compatible model."
reasoning_effort = "medium"
supported_reasoning_efforts = ["low", "medium", "high"]
context_window = 128000
truncation_token_limit = 10000
priority = 1
visibility = "list"
shell_type = "shell_command"
web_search_tool_type = "text"
supported_in_api = true
supports_reasoning_summaries = true
default_reasoning_summary = "none"
support_verbosity = true
default_verbosity = "low"
supports_parallel_tool_calls = true
supports_image_detail_original = true
supports_search_tool = true
input_modalities = ["text", "image"]

[[models]]
id = "gravity"
name = "Custom Combo"
provider = "openai-local"
description = "Custom Custom Combo compatible model."
reasoning_effort = "medium"
supported_reasoning_efforts = ["low", "medium", "high"]
context_window = 128000
truncation_token_limit = 10000
priority = 1
visibility = "list"
shell_type = "shell_command"
web_search_tool_type = "text"
supported_in_api = true
supports_reasoning_summaries = true
default_reasoning_summary = "none"
support_verbosity = true
default_verbosity = "low"
supports_parallel_tool_calls = true
supports_image_detail_original = true
supports_search_tool = true
input_modalities = ["text", "image"]

[[models]]
id = "ollama/gpt-oss:120b"
name = "ollama/gpt-oss:120b"
provider = "openai-local"
description = "ollama/gpt-oss:120b"
reasoning_effort = "medium"
supported_reasoning_efforts = ["low", "medium", "high"]
context_window = 272000
truncation_token_limit = 10000
priority = 1
visibility = "list"
shell_type = "shell_command"
web_search_tool_type = "text"
supported_in_api = true
supports_reasoning_summaries = true
default_reasoning_summary = "none"
support_verbosity = true
default_verbosity = "low"
supports_parallel_tool_calls = true
supports_image_detail_original = true
supports_search_tool = true
input_modalities = ["text", "image"]
